#pragma config(Sensor, S1,     Ult1,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Ult2,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLinks,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          Dribbler,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          motorRechts,   tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*	
	This code is intellectual property of Bodensee Bots j.r.t. and is not allowed to be used for commercial purposes.
	The authors are not responsible for any damage caused by the use of this code.
	Code created by:  Peer Siems, 2025 / Marlon Jost, 2025
	Soccerversion 5.0
*/

#include "hitechnic-compass.h"
#include "hitechnic-irseeker-v2.h"

#define SeekerPort S3
#define KompassPort S4

tHTMC Kompass;
tHTIRS2 Seeker;

int status = 0;
// Status: 0 = idle, 1 = 

// Variablen definieren
int dribbler_speed_ini; // Ursprüngliche Dribbler Geschwindigkeit
int dribbler_speed; // Dribbler Geschwindigkeit
int me_dir; // Roboter Richtung
int ball_dir; // Ball Richtung
int dir_diff;
int ini_goal_dir; // Torwamnd Richtung
float goal_dir; // Tor Richtung
float dis_r; // Ultraschall Entfernung Rechts
float dis_l; // Ultraschall Entfernung Links

// Main Task
task main();
{
	setMotorSpeed(Dribbler, 100); // Ürsprünglicher Dribbler Speed
	dribbler_speed_ini = getMotorRPM(Dribbler); // Ursprünglicher Dribbler Speed festlegen
	
	initSensor (&Kompass, KompassPort);
	readSensor (&Kompass);
	ini_goal_dir = Kompass.heading;
	Kompass.offset = goal_dir;

	while (true)
	{
		// Sensoren Auslesen
		readSensor(&Kompass);
		me_dir = Kompass.relativeHeading;

		readSensor (&Seeker);
		ball_dir = Seeker.acDirection


	}

}

