#pragma config(Sensor, S1,     Ult1,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Ult2,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLinks,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          Dribbler,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          motorRechts,   tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is intellectual property of Bodensee Bots j.r.t. and is not allowed to be used for commercial purposes.
// The authors are not responsible for any damage caused by the use of this code.
//This code may be used for educational Purposes
// Code created by:  Peer Siems, 2025 / Marlon Jost, 2025
// Soccerversion 9 STABLE RELEASE

#include "hitechnic-compass.h"
#include "hitechnic-irseeker-v2.h"

#define SeekerPort S3
#define KompassPort S4

tHTMC Kompass;
tHTIRS2 Seeker;

int status = 0;
// STATUS: 0 = Ball suchen, 1 = habe Ball, 2 = Tor anfahren

int dribbler_speed = 0;
int dribbler_speed_ini = 0;

int TorSeite;

int TorOKOKOK = false;
int TorWinkel = 0;
int DribblerS;
int DribblerSpeedBall;
long TorRichtung;
long Abweichung;
long BallRichtung;

float TorFinalRichtung;
float Ultlinks;
float Ulthinten;

bool BallDa = false;
bool TorOK = false;

int guckoblinksoderrechts(int status)
{

	//while((BallDa == true) && (status == 3))
	//{

	displayBigTextLine (4, "US: %d %d ", Ultlinks, Ulthinten);


	if (DribblerS >= DribblerSpeedBall)
	{
		TorSeite = 0;
		BallDa = false;
		status	= 0;

	}


	Ulthinten = getUSDistance(Ult1);
	Ultlinks = getUSDistance(Ult2);

	if (Ultlinks > 60)
	{
		//rechts
		setMotorSpeed(motorLinks, -11);
		setMotorSpeed(motorRechts, 11);
		wait1Msec(500);
		setMotorSpeed(motorRechts, 50);
		setMotorSpeed(motorLinks, 50);
		wait1Msec(10000);
		//	status = 0;
	}

	if (Ultlinks < 40)
	{
		//links
		setMotorSpeed(motorRechts, -11);
		setMotorSpeed(motorLinks, 11);
		wait1Msec(500);
		setMotorSpeed(motorLinks, 50);
		setMotorSpeed(motorRechts, 50);
		wait1Msec(10000);
		//	status = 0;
	}

	if ((Ultlinks >= 40) && (Ultlinks <= 60)
	{
		//links
		setMotorSpeed(motorLinks, 50);
		setMotorSpeed(motorRechts, 50);
		wait1Msec(10000);
		//	status = 0;
		//	}

	}

	return(status);
}


int Toranfahrt(int status)
{

	//	while((BallDa == true) && (status == 2))
	//	{
	displayBigTextLine (4, "US: %d %d ", Ultlinks, Ulthinten);

	DribblerS = getMotorRPM(Dribbler);

	if (DribblerS >= DribblerSpeedBall)
	{
		BallDa = false;
		status	= 0;

	}

	setMotorSpeed(motorLinks, 30);
	setMotorSpeed(motorRechts, 30);
	Ulthinten = getUSDistance(Ult2);
	if (Ulthinten <= 20)
	{
		status = 3;
	}

	//}


	return(status);
}

int Tor(int status)
{

	displayBigTextLine (4, "US: %d %d ", Ultlinks, Ulthinten);

	/*
	if ((Abweichung > -5) && (Abweichung < 0))
	{
	setMotorSpeed(motorLinks, 5);
	setMotorSpeed(motorRechts, -5);
	}
	*/
	if ((Abweichung < -5) && (Abweichung > -180))
	{
		setMotorSpeed(motorLinks, 5);
		setMotorSpeed(motorRechts, -5);
	}

	else if ((Abweichung > 5) && (Abweichung < 180)) //hi
	{
		setMotorSpeed(motorLinks, -5);
		setMotorSpeed(motorRechts, 5);
	}

	else if ((Abweichung < 5) && (Abweichung > -5))
	{

		setMotorSpeed(motorLinks, 0);
		setMotorSpeed(motorRechts,0);

		// jetzt k?nnen korrekt US Werte gemessen werden
		Ulthinten = getUSDistance (Ult2);
		Ultlinks = getUSDistance (Ult1);
		status = 2;

	}
	return status;
}

int Ballsuchen(int status)
{
	DribblerS = getMotorRPM(Dribbler);

	displayBigTextLine (4, "US: %d %d ", Ultlinks, Ulthinten);

	if (BallDa == false)
	{
		//Ball suchen
		if ((BallRichtung == 5) )   //|| (BallRichtung == 4) || (BallRichtung == 6)) // Ball vorne
		{
			setMotorSpeed (motorLinks, 23);
			setMotorSpeed (motorRechts, 23);
		}
		if (BallRichtung == 4) // Ball rechts
		{
			setMotorSpeed (motorLinks, -10);
			setMotorSpeed (motorRechts, 10);
		}
		if (BallRichtung == 6) // Ball links
		{
			setMotorSpeed (motorLinks, 10);
			setMotorSpeed (motorRechts, -10);
		}
		if (BallRichtung > 6)
		{
			setMotorSpeed (motorLinks, 17);
			setMotorSpeed (motorRechts, -17);
		}
		if (BallRichtung < 4)
		{
			setMotorSpeed (motorLinks, -17);
			setMotorSpeed (motorRechts, 17);
		}

	}

	if ((DribblerS <= DribblerSpeedBall) && (DribblerS > 100))
	{
		BallDa = true;
		status	= 1;

	}

	return status;
}

task main()
{
	status = 0;


	// Senorinitialisierung
	initSensor (&Kompass, KompassPort);
	readSensor (&Kompass);
	TorRichtung = Kompass.heading;
	Kompass.offset = TorRichtung;

	initSensor (&Seeker, SeekerPort);

	// dribbler_speed_ini = getMotorRPM(Dribbler);

	waitForButtonPress();
	setMotorSpeed(Dribbler, 100);
	setMotorSpeed (motorLinks, 40);
	setMotorSpeed (motorRechts, 40);
	wait1Msec(800);
	DribblerS = getMotorRPM(Dribbler);
	DribblerSpeedBall = (DribblerS*0.95);
	// clearTimer (timer1);

	while (true)
	{
		//sensoren
		readSensor (&Kompass);
		Abweichung = Kompass.relativeHeading;

		readSensor (&Seeker);
		BallRichtung = Seeker.acDirection;

		Ulthinten = getUSDistance(Ult1);
		Ultlinks = getUSDistance(Ult2);

		//Sensorwerte anzeigen
		eraseDisplay ();
		displayBigTextLine (0, "Abweich:%d", Abweichung);
		displayBigTextLine (2, "Ball:%d Start:%d", BallRichtung, TorRichtung);
		displayBigTextLine (4, "US: %d %d ", Ultlinks, Ulthinten);
		displayBigTextLine (6, "Dribbler :%d", DribblerS);
		if ( BallDa == false) displayBigTextLine (10, "Ballsuche    ");
		if ((BallDa == true) && (TorOK == false)) displayBigTextLine (10, "Pos. best.   ");
		if ((BallDa == true) && (TorOK == true )) displayBigTextLine (10, "fahre zum Tor");






		if(status == 0)
		{
			status = Ballsuchen(status);
		}

		if(status == 1)
		{
			status = Tor(status);
		}
		if(status == 2)
		{
			status = Toranfahrt(status);
		}

		if(status == 3)
		{
			status = guckoblinksoderrechts(status);
		}

	}


}

