#pragma config(Sensor, S1,     Ult1,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Ult2,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLinks,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          Dribbler,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          motorRechts,   tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-compass.h"
#include "hitechnic-irseeker-v2.h"

#define SeekerPort S3
#define KompassPort S4

tHTMC Kompass;
tHTIRS2 Seeker;

int DribblerS;

long TorRichtung;
long Abweichung;

long BallRichtung;

void TorFinal()
{
	while ((DribblerS < 220) && (DribblerS > 150))
	{
		setMotorSpeed(motorLinks, 20);
		setMotorSpeed(motorRechts, 20);
		if ((Ult1 < 150) && (Ult1 > 40))
		{
			setMotorSpeed(motorLinks, 20);
			setMotorSpeed(motorRechts, -20);
			wait1Msec(1000)
			setMotorSpeed(motorLinks, 20);
			setMotorSpeed(motorRechts, 20);
			waitUntil((Ult1 >= 35) && (Ult1 >= 50))
		}
	}
}

void Tor()
{
	if ((Abweichung > -5) && (Abweichung < 2))
	{
		setMotorSpeed(motorLinks, 5);
		setMotorSpeed(motorRechts, -5);
		wait1Msec(20);
	}

	if ((Abweichung < -5) && (Abweichung > -180))
	{
		setMotorSpeed(motorLinks, 5);
		setMotorSpeed(motorRechts, -5);
		wait1Msec(20);
	}

	if ((Abweichung > 5) && (Abweichung < 180)) //hi
	{
		setMotorSpeed(motorLinks, -5);
		setMotorSpeed(motorRechts, 5);
		wait1Msec(20);
	}

	if ((Abweichung < 3) && (Abweichung > -3))
	{
		TorFinal();
	}
}

task main();
{
	setMotorSpeed(Dribbler, 100);

	// Senorinitialisierung
	initSensor (&Kompass, KompassPort);
	readSensor (&Kompass);
	TorRichtung = Kompass.heading;
	Kompass.offset = TorRichtung;

	initSensor (&Seeker, SeekerPort);

	clearTimer (timer1);

	while (true)
	{

		//Sensorwerte auslesen
		readSensor (&Kompass);
		Abweichung = Kompass.relativeHeading;

		readSensor (&Seeker);
		BallRichtung = Seeker.acDirection;

		//Sensorwerte anzeigen
		eraseDisplay ();
		displayBigTextLine (0, "Abweich:%d", Abweichung);
		displayBigTextLine (2, "Ball   :%d", BallRichtung);
		displayBigTextLine (8, "Start   :%d", TorRichtung);
		displayBigTextLine (4, "Dribbler   :%d", getMotorSpeed(Dribbler));
		displayBigTextLine (6, "RPM   :%d", getMotorRPM(Dribbler));

		//Ball suchen
		if ((BallRichtung == 5) )   //|| (BallRichtung == 4) || (BallRichtung == 6)) // Ball vorne
		{
			setMotorSpeed (motorLinks, 23);
			setMotorSpeed (motorRechts, 23);
		}
		if (BallRichtung == 4) // Ball rechts
		{
			setMotorSpeed (motorLinks, -10);
			setMotorSpeed (motorRechts, 10);
		}
		if (BallRichtung == 6) // Ball links
		{
			setMotorSpeed (motorLinks, 10);
			setMotorSpeed (motorRechts, -10);
		}
		if (BallRichtung > 6)
		{
			setMotorSpeed (motorLinks, 23);
			setMotorSpeed (motorRechts, -23);
		}
		if (BallRichtung < 4)
		{
			setMotorSpeed (motorLinks, -23);
			setMotorSpeed (motorRechts, 23);
		}
		//auf Ball fahren
		//Tor ausrichten

		DribblerS = getMotorRPM(Dribbler);

		if ((DribblerS < 220) && (DribblerS > 150))
		{
			Tor();
		}








		//zum Tor fahren


		wait1Msec (50);
	}



	//Ball stalken

}
