#pragma config(Sensor, S1,     Ult1,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Ult2,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLinks,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          Dribbler,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          motorRechts,   tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*	
	This code is intellectual property of Bodensee Bots j.r.t. and is not allowed to be used for commercial purposes.
	The authors are not responsible for any damage caused by the use of this code.
	Code created by:  Peer Siems, 2025 / Marlon Jost, 2025
	Soccerversion 8xx !! EXPERIMENTAL !! not usable
*/

#include "hitechnic-compass.h"
#include "hitechnic-irseeker-v2.h"

#define SeekerPort S3
#define KompassPort S4

tHTMC Kompass;
tHTIRS2 Seeker;

int status = 0;
// Status: 0 = idle, 1 = suche ball, 2 = habe Ball, 

// Variablen definieren
int dribbler_speed_ini; // Ursprüngliche Dribbler Geschwindigkeit
int dribbler_speed; // Dribbler Geschwindigkeit
int me_dir; // Roboter Richtung
int ball_dir; // Ball Richtung
int dir_diff;
int ini_goal_dir; // Torwamnd Richtung
int toleranz = 10;
int motor_speed = 25;
float goal_dir; // Tor Richtung
float dis_r; // Ultraschall Entfernung Rechts
float dis_h; // Ultraschall Entfernung Links

void rotate_to_dir(int tar_dir, bool drive_forward)

// Main Task
task main();
{
	setMotorSpeed(Dribbler, 100); // Ürsprünglicher Dribbler Speed
	dribbler_speed_ini = getMotorRPM(Dribbler); // Ursprünglicher Dribbler Speed festlegen
	
	initSensor (&Kompass, KompassPort);
	readSensor (&Kompass);
	ini_goal_dir = Kompass.heading;
	Kompass.offset = goal_dir;

	while (true)
	{
		// Sensoren Auslesen
		readSensor(&Kompass);
		me_dir = Kompass.relativeHeading;

		readSensor (&Seeker);
		ball_dir = Seeker.acDirection

		dribbler_speed = getMotorRPM(Dribbler);

		dis_h = getUSDistance(Ult1);
		dis_r = getUSDistance(Ult2);

		// Main
		if ((dribbler_speed < dribbler_speed_ini + toleranz) && (dribbler_speed > dribbler_speed_ini - toleranz))
		{
			status = 2 // habe Ball

			if (me_dir == ini_goal_dir)
			{
				dis_h
				dis_r
				//hier Peer's Rechnung für Torwinkel einfügen
			
			
			
			
				
			}
			else
			{
				
			}
			// werte nehmen
			// Tor Berechnen
			// auf Tor korregierenw
			// ins tor fahren 	
		}
		else
		{
			status = 1 // suche Ball

			// Ball suchen
			if (BallRichtung == 5)
			{
				setMotorSpeed(motorLinks, motor_speed);
				setMotorSpeed(motorRechts, motor_speed);
			}
			else if (BallRichtung < 5) // Ball rechts
			{
				setMotorSpeed(motorLinks, -motor_speed);
				setMotorSpeed(motorRechts, motor_speed);
			}
			else if (BallRichtung > 5) // Ball links
			{
				setMotorSpeed(motorLinks, motor_speed);
				setMotorSpeed(motorRechts, -motor_speed);
			}
			else
			{
				setMotorSpeed(motorLinks, -motor_speed);
				setMotorSpeed(motorRechts, motor_speed);
			}
		}
		wait1Msec (50);
	}

}

