#pragma config(Sensor, S1,     Ult1,           sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Ult2,           sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          motorLinks,    tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          Dribbler,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          motorRechts,   tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is intellectual property of Bodensee Bots j.r.t. and is not allowed to be used for commercial purposes.
// The authors are not responsible for any damage caused by the use of this code.
// Code created by:  Peer Siems, 2025 / Marlon Jost, 2025
// Soccerversion 5.0

#include "hitechnic-compass.h"
#include "hitechnic-irseeker-v2.h"

#define SeekerPort S3
#define KompassPort S4

tHTMC Kompass;
tHTIRS2 Seeker;

int status = 0;
// STATUS: 0 = Ball suchen, 1 = habe Ball, 2 = Tor anfahren

int dribbler_speed = 0;
int dribbler_speed_ini = 0;

long TorRichtung;
long Abweichung;
long BallRichtung;

float TorFinalRichtung;
float USlinks;
float UShinten;

bool BallDa = false;
bool TorOK = false;

void TorFinal()
{
	if (Abweichung <= TorFinalRichtung-3)
	{
		setMotorSpeed(motorLinks, 10);
		setMotorSpeed(motorRechts, -10);
		TorOK = false;
	}
	if (Abweichung >= TorFinalRichtung+3)
	{
		setMotorSpeed(motorLinks, -10);
		setMotorSpeed(motorRechts, 10);
		TorOK = false;
	}

	if ((Abweichung >= TorFinalRichtung-5) && (Abweichung <= TorFinalRichtung+5))
	{
		setMotorSpeed(motorLinks, 20);
		setMotorSpeed(motorRechts, 20);
		TorOK = true;
	}
}

void Tor()
{
	if ((Abweichung > -5) && (Abweichung < 2))
	{
		setMotorSpeed(motorLinks, 5);
		setMotorSpeed(motorRechts, -5);
	}

	else if ((Abweichung < -5) && (Abweichung > -180))
	{
		setMotorSpeed(motorLinks, 5);
		setMotorSpeed(motorRechts, -5);
	}

	else if ((Abweichung > 5) && (Abweichung < 180)) //hi
	{
		setMotorSpeed(motorLinks, -5);
		setMotorSpeed(motorRechts, 5);
	}

	else if ((Abweichung < 3) && (Abweichung > -3))
	{
		TorOK = true;
		setMotorSpeed(motorLinks, 0);
		setMotorSpeed(motorRechts,0);

    // jetzt k�nnen korrekt US Werte gemessen werden
		UShinten = getUSDistance (Ult2);
		USlinks = getUSDistance (Ult1);
	}
}

task main();
{
	setMotorSpeed(Dribbler, 100);

	// Senorinitialisierung
	initSensor (&Kompass, KompassPort);
	readSensor (&Kompass);
	TorRichtung = Kompass.heading;
	Kompass.offset = TorRichtung;

	initSensor (&Seeker, SeekerPort);

	// dribbler_speed_ini = getMotorRPM(Dribbler);

	clearTimer (timer1);

	while (true)
	{
		//Sensorwerte auslesen
		readSensor (&Kompass);
		Abweichung = Kompass.relativeHeading;

		readSensor (&Seeker);
		BallRichtung = Seeker.acDirection;

		DribblerS = getMotorRPM(Dribbler);


		//Sensorwerte anzeigen
		eraseDisplay ();
		displayBigTextLine (0, "Abweich:%d", Abweichung);
		displayBigTextLine (2, "Ball:%d Start:%d", BallRichtung, TorRichtung);
		displayBigTextLine (4, "US h:%d l:%d", UShinten, USlinks);
		displayBigTextLine (8, "Dribbler :%d", DribblerS);
		if ( BallDa == false) displayBigTextLine (10, "Ballsuche    ");
		if ((BallDa == true) && (TorOK == false)) displayBigTextLine (10, "Pos. best.   ");
		if ((BallDa == true) && (TorOK == true )) displayBigTextLine (10, "fahre zum Tor");

		if ((dribbler_speed < 215) && (dribbler_speed > 150))
		{
			status = 1; // habe Ball
		}
		else
		{
			status = 0; // Ball suchen
		}



		if ((DribblerS < 215) && (DribblerS > 150))
		{
			BallDa = true;
		}
		else
		{
			BallDa = false;
		}

		//Strategie
		if ((BallDa == true) && (TorOK == false))
		{
			Tor();
		}

		if ((BallDa == true) && (TorOK == true))
		{
			TorFinalRichtung = atan2(125-Ult1, 190-Ult2);
			TorFinal();
		}

		if (BallDa == false)
		{
			//Ball suchen
			if ((BallRichtung == 5) )   //|| (BallRichtung == 4) || (BallRichtung == 6)) // Ball vorne
			{
				setMotorSpeed (motorLinks, 23);
				setMotorSpeed (motorRechts, 23);
			}
			if (BallRichtung == 4) // Ball rechts
			{
				setMotorSpeed (motorLinks, -10);
				setMotorSpeed (motorRechts, 10);
			}
			if (BallRichtung == 6) // Ball links
			{
				setMotorSpeed (motorLinks, 10);
				setMotorSpeed (motorRechts, -10);
			}
			if (BallRichtung > 6)
			{
				setMotorSpeed (motorLinks, 23);
				setMotorSpeed (motorRechts, -23);
			}
			if (BallRichtung < 4)
			{
				setMotorSpeed (motorLinks, -23);
				setMotorSpeed (motorRechts, 23);
			}
		}

		// mit Motorwerten fahren
		wait1Msec (50);
	}

}
